version: '3'

services:
  node-exporter:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-exporter
    container_name: node-exporter
    image: seanly/kubeset:node-exporter-v1.7.0-1

  cadvisor:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: cadvisor
    container_name: cadvisor
    image: seanly/kubeset:cadvisor-v0.47.2-1

  k8s-sidecar:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: k8s-sidecar
    container_name: k8s-sidecar
    image: seanly/kubeset:k8s-sidecar-1.25.2-1

  alertmanager:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: alertmanager
    container_name: alertmanager
    image: seanly/kubeset:alertmanager-v0.26.0-1

  prometheus:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prometheus
    container_name: prometheus
    image: seanly/kubeset:prometheus-v2.48.1-1

  prometheus-operator:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prometheus-operator
    container_name: prometheus-operator
    image: seanly/kubeset:prometheus-operator-v0.70.0-1

  kube-webhook-certgen:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: kube-webhook-certgen
    container_name: kube-webhook-certgen
    image: seanly/kubeset:kube-webhook-certgen-v1.5.1-1

  kube-state-metrics:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: kube-state-metrics
    container_name: kube-state-metrics
    image: seanly/kubeset:kube-state-metrics-v2.10.1-1

  admission-webhook:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: admission-webhook
    container_name: admission-webhook
    image: seanly/kubeset:admission-webhook-v0.70.0-1

  prometheus-config-reloader:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prometheus-config-reloader
    container_name: prometheus-config-reloader
    image: seanly/kubeset:prometheus-config-reloader-v0.50.0-1

networks:
  default:
    name: opsbox-network
    external: true
