global:
  scrape_interval:     60s
  evaluation_interval: 60s
             
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          instance: prometheus
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: oes-1
                                                                       
  - job_name: node-cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: oes-1
                                                                       
