version: '3'

services:
  grafana:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VERSION=9.5.1
    container_name: grafana
    image: seanly/opsmetrics:grafana-9.5.1-1
    restart: unless-stopped
    user: '472'
    ports:
    - 3000:3000
    volumes:
      - ./base/config:/etc/grafana
    # network_mode: "host"
    labels:
    - "traefik.http.routers.grafana.rule=Host(`grafana.opsbox.dev`)"
    - "traefik.http.routers.grafana.tls=true"
    - "traefik.http.routers.grafana.tls.certResolver=le"
networks:
  default:
    name: opsbox-network
    external: true
