---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-nodeport
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort

