version: "3"
services:
  rke2up:
    build:
      context: ./
      target: rke2up
    image: seanly/rke2up

  rke2-126:
    build:
      context: ./
      args:
        RKE2_VERSION: v1.26.14+rke2r1
    image: seanly/rke2up:v1.26.14-rke2r1

  rke2-127:
    build:
      context: ./
      args:
        RKE2_VERSION: v1.27.11+rke2r1
    image: seanly/rke2up:v1.27.11-rke2r1

  rke2-128:
    build:
      context: ./
      args:
        RKE2_VERSION: v1.28.7+rke2r1
    image: seanly/rke2up:v1.28.7-rke2r1
