[[servers]]
host = "openldap"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "uid=ldapadmin,ou=users,dc=opsbox"
bind_password = 'xxx'
search_filter = "(uid=%s)"
search_base_dns = ["ou=users,dc=opsbox"]
group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
group_search_base_dns = ["ou=groups,dc=opsbox"]
group_search_filter_user_attribute = "uid"

[servers.attributes]
name = "cn"
surname = "sn"
username = "uid"
email =  "mail"

