version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.35.0
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    labels:
    - "traefik.http.routers.prometheus.rule=Host(`prometheus.opsbox.dev`)"
    - "traefik.http.routers.prometheus.tls=true"
    - "traefik.http.routers.prometheus.tls.certResolver=le"

networks:
  default:
    name: opsbox-network
    external: true

volumes:
    prometheus-data:
