loki:
  rbac:
    pspEnabled: false
  image:
    repository: seanly/opsmetrics
    tag: loki-2.5.0-1
  enabled: true
  isDefault: true
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.opsbox.dev/logging
            operator: In
            values:
            - "loki"
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 150Gi
    subPath: ""
    storageClassName: local-volume

  service:
    type: NodePort
    nodePort: 30310
    port: 3100

  resources: 
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 500Mi
  config:
    auth_enabled: false
    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    limits_config:
      retention_period: 15d
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 336h
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150


promtail:
  image:
    registry: docker.io
    repository: seanly/opsmetrics
    tag: promtail-2.5.0-1
  enabled: true
  config:
    lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push
  extraVolumes:
    - hostPath:
        path: /data/
      name: data
  extraVolumeMounts:
    - mountPath: /data
      name: data
      readOnly: true
  resources: 
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    value: "true"
  - effect: NoSchedule
    key: node-role.kubernetes.io/master

fluent-bit:
  enabled: false
grafana:
  enabled: false
prometheus:
  enabled: false
filebeat:
  enabled: false
logstash:
  enabled: false
